"""
aeropad.polar.kriging
=====================
Single-fidelity Kriging (Gaussian Process Regression) full-range polar
reconstruction from sparse high-fidelity samples.

The validated workflow is the uniform-20° sampling rule: 19 training
stations across ±180° reconstruct the full polar with R² ≥ 0.99 wherever
the polar carries no sharp features narrower than the station spacing —
a ~74% reduction in CFD cost against a 5°-resolved sweep, halved again
to 10 unique evaluations for symmetric airfoils via geometric mirroring.

Sharp low-Mach lift-stall peaks that fall between stations are the known
limitation; two supplementary stations at ±15° bracket the stall and
restore competitive accuracy (see :func:`recommended_stations`).

Classes
-------
:class:`KrigingReconstructor`
    Fit / predict wrapper with automatic kernel selection (RBF vs.
    periodic ExpSineSquared by cross-validated RMSE).

Functions
---------
:func:`uniform_stations`         — the uniform-spacing training grid
:func:`recommended_stations`     — grid + stall-bracketing supplements
:func:`sample_training`          — extract training rows from a DataFrame
:func:`mirror_symmetric`         — halve CFD cost for symmetric airfoils
:func:`loo_cv`                   — leave-one-out evaluation for sparse refs
"""

from __future__ import annotations

import warnings
from typing import Optional

import numpy as np
import pandas as pd

from sklearn.exceptions import ConvergenceWarning
from sklearn.gaussian_process import GaussianProcessRegressor
from sklearn.gaussian_process.kernels import (
    RBF, ConstantKernel as C, ExpSineSquared,
)
from sklearn.model_selection import KFold, cross_val_score
from sklearn.preprocessing import StandardScaler

# The CV kernel sweep intentionally probes hyperparameter-bound edges;
# sklearn's ConvergenceWarnings there are expected noise, not defects.
warnings.filterwarnings("ignore", category=ConvergenceWarning)


# ── Training-station design ──────────────────────────────────────────

def uniform_stations(spacing: float = 20.0,
                     lo: float = -180.0,
                     hi: float = 180.0) -> np.ndarray:
    """Uniformly spaced angle-of-attack training stations.

    The uniform-20° rule (19 stations over ±180°) is the validated
    default: rule-based, requiring no per-airfoil judgement, and
    empirically the best-performing configuration among uniform and
    region-densified alternatives.
    """
    n = int(round((hi - lo) / spacing)) + 1
    return np.linspace(lo, hi, n)


def recommended_stations(spacing: float = 20.0,
                         bracket_stall: bool = False,
                         alpha_stall: float = 15.0) -> np.ndarray:
    """Training stations with optional stall-bracketing supplements.

    With ``bracket_stall=True``, two supplementary stations at
    ``±alpha_stall`` are added to the uniform grid. This addresses the
    known sharp-stall limitation: at low Mach, lift peaks near ±15° fall
    between the 0° and ±20° stations of the uniform grid and the GPR
    posterior undershoots them. Two extra evaluations close the gap.
    """
    base = uniform_stations(spacing)
    if not bracket_stall:
        return base
    extra = np.array([-abs(alpha_stall), abs(alpha_stall)])
    return np.unique(np.concatenate([base, extra]))


def sample_training(df: pd.DataFrame,
                    value_col: str,
                    stations: np.ndarray,
                    aoa_col: str = "AoA",
                    tol: float = 0.51) -> pd.DataFrame:
    """Extract training rows whose AoA lies within ``tol`` of a station.

    Returns the subset of ``df`` (rows with non-null ``value_col``)
    closest to each requested station. Stations with no matching row
    within ``tol`` degrees are skipped with a warning.
    """
    rows = []
    valid = df.dropna(subset=[value_col])
    for s in stations:
        d = (valid[aoa_col] - s).abs()
        i = d.idxmin() if len(d) else None
        if i is not None and d.loc[i] <= tol:
            rows.append(i)
        else:
            warnings.warn(
                f"No sample within {tol}° of requested station {s:+.1f}°; "
                f"station skipped.", UserWarning)
    return valid.loc[sorted(set(rows))]


def mirror_symmetric(df: pd.DataFrame,
                     coefficient: str,
                     value_col: str,
                     aoa_col: str = "AoA") -> pd.DataFrame:
    """Mirror positive-branch samples of a symmetric airfoil.

    For symmetric airfoils, ``CL(-α) = -CL(α)`` and ``CD(-α) = CD(α)``:
    only the non-negative angle-of-attack stations require direct CFD
    evaluation, and the negative branch is generated by sign rules. This
    halves the CFD cost of the Kriging route (10 unique evaluations for
    the uniform-20° rule instead of 19).

    Parameters
    ----------
    df : DataFrame with non-negative AoA samples.
    coefficient : ``"CL"`` (antisymmetric) or ``"CD"`` (symmetric).
    """
    pos = df.dropna(subset=[value_col]).copy()
    pos = pos[pos[aoa_col] >= 0.0]
    neg = pos[pos[aoa_col] > 0.0].copy()
    neg[aoa_col] = -neg[aoa_col]
    if coefficient.upper() == "CL":
        neg[value_col] = -neg[value_col]
    elif coefficient.upper() != "CD":
        raise ValueError("coefficient must be 'CL' or 'CD'")
    out = pd.concat([neg, pos]).sort_values(aoa_col).reset_index(drop=True)
    return out


# ── Kernel selection ────────────────────────────────────────────────

def _select_kernel(X_s: np.ndarray,
                   y: np.ndarray,
                   random_state: int = 42):
    """Cross-validated kernel selection: RBF grid vs. periodic grid.

    Both candidate families are swept over initial hyperparameters and
    scored by K-fold CV RMSE; the winning fitted kernel is returned as
    the initialisation for the final fit. Aerodynamic polars over ±180°
    are periodic by construction, so the ExpSineSquared family is a
    physically-motivated candidate; empirically, RBF wins on most
    coefficient/condition combinations.
    """
    cv = KFold(n_splits=min(5, len(X_s)), shuffle=True,
               random_state=random_state)

    best_rmse, best_kernel = np.inf, None

    for ls in np.logspace(-2, 2, 10):
        k = C(1.0, (1e-3, 1e3)) * RBF(ls, length_scale_bounds=(1e-2, 1e3))
        m = GaussianProcessRegressor(kernel=k, n_restarts_optimizer=2,
                                     random_state=random_state,
                                     normalize_y=True)
        s = cross_val_score(m, X_s, y, cv=cv,
                            scoring="neg_mean_squared_error")
        r = float(np.sqrt(-s.mean()))
        if r < best_rmse:
            m.fit(X_s, y)
            best_rmse, best_kernel = r, m.kernel_

    for p in np.linspace(10, 100, 10):
        k = C(1.0, (1e-3, 1e3)) * ExpSineSquared(
            1.0, p,
            length_scale_bounds=(1e-2, 1e3),
            periodicity_bounds=(1e-2, 1e3))
        m = GaussianProcessRegressor(kernel=k, n_restarts_optimizer=2,
                                     random_state=random_state,
                                     normalize_y=True)
        s = cross_val_score(m, X_s, y, cv=cv,
                            scoring="neg_mean_squared_error")
        r = float(np.sqrt(-s.mean()))
        if r < best_rmse:
            m.fit(X_s, y)
            best_rmse, best_kernel = r, m.kernel_

    return best_kernel


# ── Reconstructor ───────────────────────────────────────────────────

class KrigingReconstructor:
    """Single-fidelity GPR reconstruction of one aerodynamic coefficient.

    Parameters
    ----------
    kernel : {"auto", "rbf", "periodic"}
        ``"auto"`` performs cross-validated selection between the RBF
        and periodic families (recommended). Fixed choices skip the CV.
    n_restarts : int
        Restarts of the L-BFGS-B hyperparameter optimiser in the final
        fit (multi-start optimisation of the log-marginal likelihood).
    random_state : int
        Seed for restart draws and CV shuffling; fixed by default so a
        given training set always produces an identical model.

    Examples
    --------
    >>> rec = KrigingReconstructor()
    >>> rec.fit(alpha_train, cl_train)
    >>> cl_hat, cl_std = rec.predict(alpha_grid, return_std=True)
    """

    def __init__(self,
                 kernel: str = "auto",
                 n_restarts: int = 8,
                 random_state: int = 42) -> None:
        self.kernel_choice = kernel
        self.n_restarts = n_restarts
        self.random_state = random_state
        self._scaler: Optional[StandardScaler] = None
        self._model: Optional[GaussianProcessRegressor] = None

    # -- fitting -----------------------------------------------------

    def fit(self, alpha: np.ndarray, y: np.ndarray) -> "KrigingReconstructor":
        alpha = np.asarray(alpha, dtype=float).reshape(-1, 1)
        y = np.asarray(y, dtype=float)

        self._scaler = StandardScaler()
        X_s = self._scaler.fit_transform(alpha)

        if self.kernel_choice == "auto":
            kernel = _select_kernel(X_s, y, self.random_state)
        elif self.kernel_choice == "rbf":
            kernel = C(1.0, (1e-3, 1e3)) * RBF(1.0, (1e-2, 1e3))
        elif self.kernel_choice == "periodic":
            kernel = C(1.0, (1e-3, 1e3)) * ExpSineSquared(
                1.0, 40.0, length_scale_bounds=(1e-2, 1e3),
                periodicity_bounds=(1e-2, 1e3))
        else:
            raise ValueError(
                f"kernel must be 'auto', 'rbf' or 'periodic', "
                f"got {self.kernel_choice!r}")

        self._model = GaussianProcessRegressor(
            kernel=kernel,
            n_restarts_optimizer=self.n_restarts,
            random_state=self.random_state,
            normalize_y=True)
        self._model.fit(X_s, y)
        return self

    # -- prediction --------------------------------------------------

    def predict(self,
                alpha: np.ndarray,
                return_std: bool = False):
        if self._model is None:
            raise RuntimeError("fit() must be called before predict().")
        alpha = np.asarray(alpha, dtype=float).reshape(-1, 1)
        X_s = self._scaler.transform(alpha)
        return self._model.predict(X_s, return_std=return_std)

    @property
    def kernel_(self):
        """The fitted kernel (after :meth:`fit`)."""
        return None if self._model is None else self._model.kernel_


# ── Leave-one-out evaluation ────────────────────────────────────────

def loo_cv(alpha: np.ndarray,
           y: np.ndarray,
           random_state: int = 42) -> dict:
    """Leave-one-out cross-validation for sparse-reference conditions.

    When the available reference itself is sparse (no dense polar to
    hold out), reconstruction accuracy is quantified by LOO-CV: each
    point is predicted by a model fit on the remaining n−1 points.
    Preferred over fixed splits (arbitrary bias on a sparse set) and
    K-fold with K < n (smaller training folds, random assignment); LOO
    uses the maximum n−1 training points per fit and evaluates every
    station exactly once.

    Protocol: the kernel is selected *once* by cross-validation on the
    full dataset, then held fixed across the n per-fold refits (each
    with its own input scaler and a light 2-restart hyperparameter
    optimisation). Re-running the full kernel selection inside every
    fold would be prohibitively expensive and adds no discriminative
    value at this sample size.

    Note this is a *stricter* protocol than dense-reference evaluation:
    each held-out station must be predicted from neighbours a full grid
    spacing away. Reported metrics are conservative lower bounds.

    Returns
    -------
    dict with keys ``R2``, ``MAE``, ``RMSE``, ``y_pred``.
    """
    from .metrics import r2, mae, rmse

    alpha = np.asarray(alpha, dtype=float).reshape(-1, 1)
    y = np.asarray(y, dtype=float)
    n = len(y)

    # Kernel selection once, on the full data
    sc = StandardScaler()
    X_s = sc.fit_transform(alpha)
    kernel = _select_kernel(X_s, y, random_state)

    preds = np.empty(n)
    for i in range(n):
        mask = np.ones(n, dtype=bool)
        mask[i] = False
        sc_i = StandardScaler()
        Xtr = sc_i.fit_transform(alpha[mask])
        Xte = sc_i.transform(alpha[~mask])
        m = GaussianProcessRegressor(kernel=kernel,
                                     n_restarts_optimizer=2,
                                     random_state=random_state,
                                     normalize_y=True)
        m.fit(Xtr, y[mask])
        preds[i] = m.predict(Xte)[0]

    return {
        "R2": r2(y, preds),
        "MAE": mae(y, preds),
        "RMSE": rmse(y, preds),
        "y_pred": preds,
    }
